/**
 * ⚠️ This JSDoc is generated by AI ⚠️
 * -
 *
 * Creates a table meta object based on the row index, column index, row data,
 * column data, table data, and current state of the table.
 *
 * @param rowIndex - The current row index.
 * @param colIndex - The current column index.
 * @param rowData - The current row data.
 * @param columnData - The current column data.
 * @param tableData - The full table data.
 * @param curState - The current state of the table.
 * @param currentTableData - The current table data.
 * @return  A table meta object.
 */
export default function getTableMeta(
    rowIndex: number,
    colIndex: number,
    rowData,
    columnData,
    tableData,
    curState: DataTableState,
    currentTableData
) {
    const { columns, data, displayData, filterData, ...tableState } = curState

    return {
        rowIndex: rowIndex,
        columnIndex: colIndex,
        columnData: columnData,
        rowData: rowData,
        tableData: tableData,
        tableState: tableState,
        currentTableData: currentTableData
    }
}
