import type { ReactNode } from 'react'
import type { DataTableState } from '@src/types/state'
import type { DataTableOptions } from '@src/types/options'
import { getCollatorComparator } from '../get-collator-comparator'

/**
 * ⚠️ This JSDoc is generated by AI ⚠️
 * -
 *
 * Updates a specific cell's data in the table and refreshes the state.
 *
 * This function modifies the data of a specified cell in the table, updates the filter data,
 * and re-calculates the display data for the table. It handles custom rendering logic for the cell
 * and ensures that the filter data is correctly updated and sorted if necessary.
 *
 * @param row - The index of the row to update.
 * @param index - The index of the column to update.
 * @param value - The new value to set in the specified cell.
 * @param prevState - The previous state of the data table.
 * @param options - Configuration options for the data table.
 * @param datatableProps - The properties of the data table.
 * @param setState - A function to update the state of the data table.
 * @returns The new state of the data table after the update.
 */
export default function updateDataCol<T>(
    row: number,
    index: number,
    value: ReactNode,
    prevState: DataTableState<T>,
    options: DataTableOptions<T>
) {
    const filterData = prevState.filterData

    const columnState = prevState.columns[index]

    if (!columnState) {
        throw new Error(`Column ${index} does not exist`)
    }

    const funcResult = columnState.customBodyRender?.(
        value,
        row,
        index,
        prevState,
        () => undefined
    )

    let filterValue = prevState.data?.[row]?.data[index]

    if (typeof funcResult === 'object' && funcResult && 'props' in funcResult) {
        filterValue = funcResult.props.value
    }

    const prevFilterIndex = filterData[index]?.indexOf(
        filterValue as T[keyof T]
    )
    filterData[index]?.splice(
        prevFilterIndex ?? 0,
        1,
        filterValue as T[keyof T]
    )

    const changedData = prevState.data[row]

    if (!changedData?.data) {
        throw new Error(`Invalid cell value: ${value}`)
    }

    changedData.data[index] = value

    const newData = prevState.data
    newData[row] = changedData

    if (options.sortFilterList) {
        const comparator = getCollatorComparator()

        // @ts-expect-error  WILL FIX LATER
        filterData[index]?.sort(comparator)
    }

    return {
        data: newData,
        filterData: filterData
    }
}
