// vendors

// globals
import type { DataTableProps } from '@src/data-table.props'
import type { HandleUpdateCellValue } from '@src/hooks/use-data-table-context/components/provider/types/handle-update-cell-value'
import type {
    DataTableOptions,
    DataTableSortOrderOption
} from '@src/types/options'
import type { DataTableState } from '@src/types/state'
import type { DataItemState } from '@src/types/state/data-item'
import type React from 'react'
import buildColumns from './build-columns'
import { getCollatorComparator } from './get-collator-comparator'
import getDisplayData from './get-new-state-on-data-change/get-display-data'
import { initializeExpandedRows } from './get-new-state-on-data-change/initialize-expanded-rows'
import { initializeSelectedRows } from './get-new-state-on-data-change/initialize-selected-rows'
import { processColumnFilter } from './get-new-state-on-data-change/process-column-filter'
import sortTable from './sort-table'
import transformData from './transform-data'

enum TABLE_LOAD {
    INITIAL = 1,
    UPDATE = 2
}

/**
 * ⚠️ This JSDoc is generated by AI ⚠️
 * -
 *
 * Builds a new state object based on the latest props. This includes generating
 * the filterData, filterList, and displayData based on the columns, data, and
 * options.
 *
 * @param props - The properties of the data table.
 * @param status - The status of the data table.
 * @param dataUpdated - A boolean indicating whether the data has been updated.
 * @param options - Configuration options for the data table.
 * @param state - The current state of the data table.
 * @returns The updated state of the data table.
 */
export default function getNewStateOnDataChange<T>(
    props: {
        columns: DataTableProps<T>['columns']
        options: DataTableProps<T>['options']
    },
    dataParam: T[] | DataItemState[],
    status: TABLE_LOAD,
    dataUpdated: boolean,
    options: DataTableOptions<T>,
    state: DataTableState<T>,
    updateCellValueRef: React.RefObject<HandleUpdateCellValue | undefined>
): DataTableState<T> {
    const { columns, filterData, filterList, columnOrder } = buildColumns<T>(
        props.columns,
        state.columns,
        options.columnOrder,
        state.columnOrder
    )

    let sortIndex: number | null = null
    let sortDirection: DataTableSortOrderOption['direction'] = 'none'

    const data =
        status === TABLE_LOAD.INITIAL
            ? transformData(columns, dataParam as T[])
            : dataParam

    const rowsPerPage = options.rowsPerPage ?? state.rowsPerPage
    const page = options.page ?? state.page
    const sortOrder = options.sortOrder ?? state.sortOrder

    let tableData: DataTableState<T>['data'] = []

    columns.forEach((column, colIndex) => {
        for (let rowIndex = 0; rowIndex < data.length; rowIndex++) {
            /**
             * IF status === TABLE_LOAD.INITIAL rowDataOrStateData should be T
             * IF status === TABLE_LOAD.UPDATE rowDataOrStateData should be DataItemState
             */
            const rowDataOrStateData = data[rowIndex]

            if (!rowDataOrStateData) {
                throw new Error('rowDataOrStateData is undefined')
            }

            let value: unknown

            const isInit =
                status === TABLE_LOAD.INITIAL &&
                Array.isArray(rowDataOrStateData)

            if (isInit) {
                value = rowDataOrStateData[colIndex]
            } else if (
                typeof rowDataOrStateData === 'object' &&
                'data' in rowDataOrStateData
            ) {
                value = rowDataOrStateData?.data[colIndex]
            }

            if (typeof tableData[rowIndex] === 'undefined') {
                if (isInit) {
                    tableData.push({
                        data: rowDataOrStateData,
                        index: rowIndex
                    })
                } else if (
                    typeof rowDataOrStateData === 'object' &&
                    'data' in rowDataOrStateData
                ) {
                    tableData.push(rowDataOrStateData)
                }
            }

            processColumnFilter(
                column,
                value,
                rowIndex,
                colIndex,
                state,
                filterData
            )
        }

        if (column.filterOptions) {
            if (Array.isArray(column.filterOptions)) {
                filterData[colIndex] = column.filterOptions
            } else if (Array.isArray(column.filterOptions.names)) {
                filterData[colIndex] = column.filterOptions.names
            }
        }

        if (column.filterList) {
            filterList[colIndex] = column.filterList
        } else if ((state.filterList[colIndex]?.length ?? 0) > 0) {
            const tempFilterList = state.filterList[colIndex]

            if (!tempFilterList) {
                throw new Error('filterList must be an array')
            }

            filterList[colIndex] = tempFilterList
        }

        if (options.sortFilterList) {
            const comparator = getCollatorComparator()

            // @ts-expect-error  WILL FIX THIS LATER
            filterData[colIndex]?.sort(comparator)
        }

        if (column.name === sortOrder?.name) {
            sortDirection = sortOrder?.direction
            sortIndex = colIndex
        }
    })

    let selectedRowsData: DataTableState<T>['selectedRows'] = {
        data: [],
        lookup: {}
    }

    let expandedRowsData: DataTableState<T>['expandedRows'] = {
        data: [],
        lookup: {}
    }

    if (status === TABLE_LOAD.INITIAL) {
        selectedRowsData = initializeSelectedRows(options, state, dataUpdated)
        expandedRowsData = initializeExpandedRows(options, state, dataUpdated)
    }

    if (!options.serverSide && sortIndex !== null) {
        const sortedData = sortTable(
            tableData,
            sortIndex,
            sortDirection,
            columns[sortIndex],
            options,
            state
        )

        tableData = sortedData.data
    }

    const searchText =
        status === TABLE_LOAD.INITIAL
            ? (options?.searchText ?? state.searchText)
            : state.searchText

    const newState: DataTableState<T> = {
        ...state,
        columnOrder,
        columns,
        count: options.count ?? tableData.length,
        data: tableData,
        expandedRows: expandedRowsData,
        filterData,
        filterList,
        page,
        rowsPerPage,
        searchText,
        selectedRows: selectedRowsData,
        sortOrder
    }

    return {
        ...newState,
        displayData: getDisplayData(
            columns,
            tableData,
            filterList,
            searchText,
            newState,
            options,
            updateCellValueRef
        )
    }
}
